/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  Role: "ADMIN" | "USER"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Link: { // root type
    category?: string | null; // String
    description?: string | null; // String
    id?: number | null; // Int
    imageUrl?: string | null; // String
    title?: string | null; // String
    url?: string | null; // String
    userId?: number | null; // Int
  }
  Mutation: {};
  Query: {};
  User: { // root type
    email?: string | null; // String
    id?: number | null; // Int
    image?: string | null; // String
    name?: string | null; // String
    role?: NexusGenEnums['Role'] | null; // Role
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Link: { // field return type
    category: string | null; // String
    description: string | null; // String
    id: number | null; // Int
    imageUrl: string | null; // String
    title: string | null; // String
    url: string | null; // String
    userId: number | null; // Int
  }
  Mutation: { // field return type
    createLink: NexusGenRootTypes['Link']; // Link!
    deleteLink: NexusGenRootTypes['Link']; // Link!
    updateLink: NexusGenRootTypes['Link']; // Link!
  }
  Query: { // field return type
    link: NexusGenRootTypes['Link']; // Link!
    links: Array<NexusGenRootTypes['Link'] | null>; // [Link]!
    user: NexusGenRootTypes['User']; // User!
    users: Array<NexusGenRootTypes['User'] | null>; // [User]!
  }
  User: { // field return type
    email: string | null; // String
    favorites: Array<NexusGenRootTypes['Link'] | null> | null; // [Link]
    id: number | null; // Int
    image: string | null; // String
    name: string | null; // String
    role: NexusGenEnums['Role'] | null; // Role
  }
}

export interface NexusGenFieldTypeNames {
  Link: { // field return type name
    category: 'String'
    description: 'String'
    id: 'Int'
    imageUrl: 'String'
    title: 'String'
    url: 'String'
    userId: 'Int'
  }
  Mutation: { // field return type name
    createLink: 'Link'
    deleteLink: 'Link'
    updateLink: 'Link'
  }
  Query: { // field return type name
    link: 'Link'
    links: 'Link'
    user: 'User'
    users: 'User'
  }
  User: { // field return type name
    email: 'String'
    favorites: 'Link'
    id: 'Int'
    image: 'String'
    name: 'String'
    role: 'Role'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createLink: { // args
      category: string; // String!
      description: string; // String!
      imageUrl: string; // String!
      title: string; // String!
      url: string; // String!
    }
    deleteLink: { // args
      id: number; // Int!
    }
    updateLink: { // args
      category?: string | null; // String
      description?: string | null; // String
      id?: number | null; // Int
      imageUrl?: string | null; // String
      title?: string | null; // String
      url?: string | null; // String
    }
  }
  Query: {
    link: { // args
      id: number; // Int!
    }
    user: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}